"""
predictor.py — Model Inference
Krish Jani (kj2743) — Serving Lead
ECE-GY 9183 MLOps, Spring 2026

THREE MODES — controlled by two flags at the top of this file:

MODE 1 — STUB (USE_STUB_MODEL = True)
    Keyword matching, no real model. 0.35ms latency.
    Used for integration testing only.

MODE 2 — REAL SBERT + LIGHTGBM (USE_STUB_MODEL = False, USE_ONNX = False)
    Real SBERT all-MiniLM-L6-v2 + LightGBM classifier.
    ~50-150ms latency depending on hardware.
    This is the baseline serving option.

MODE 3 — ONNX SBERT + LIGHTGBM (USE_STUB_MODEL = False, USE_ONNX = True)
    SBERT encoder exported to ONNX format via export_onnx.py.
    ~30-80ms latency — faster than MODE 2 because ONNX runtime
    is more optimized than PyTorch for CPU inference.
    This is the model-level optimization serving option.

Switching modes:
    Baseline  : USE_STUB_MODEL = False, USE_ONNX = False
    ONNX      : USE_STUB_MODEL = False, USE_ONNX = True
    Stub      : USE_STUB_MODEL = True  (USE_ONNX is ignored)
"""

import os
import logging
import random
import time
from pathlib import Path
from dataclasses import dataclass

import numpy as np

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration — change these two flags to switch modes
# ---------------------------------------------------------------------------

USE_STUB_MODEL = os.getenv("USE_STUB_MODEL", "false").lower() == "true"
USE_ONNX       = os.getenv("USE_ONNX", "false").lower() == "true"

MODEL_PATH         = Path(os.getenv("MODEL_PATH",         "/models/lgbm_classifier_v1.pkl"))
LABEL_ENCODER_PATH = Path(os.getenv("LABEL_ENCODER_PATH", "/models/label_encoder.pkl"))
ONNX_MODEL_PATH    = Path(os.getenv("ONNX_MODEL_PATH",    "/models/sbert_onnx.onnx"))

VALID_LABELS = [
    "Lecture Notes", "Problem Set", "Exam", "Syllabus",
    "Reading", "Solution", "Project", "Recitation", "Lab", "Other",
]

AUTO_APPLY_THRESHOLD = 0.85
SUGGEST_THRESHOLD    = 0.50


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class PredictionResult:
    predicted_tag:   str
    confidence:      float
    action:          str
    top_predictions: list[dict]
    explanation:     str | None
    model_version:   str
    latency_ms:      float


# ---------------------------------------------------------------------------
# Predictor class
# ---------------------------------------------------------------------------

class Predictor:

    def __init__(self):
        self.model_version = "stub_v0"
        self.sbert_model   = None
        self.onnx_session  = None
        self.lgbm_model    = None
        self.label_encoder = None
        self.tokenizer     = None

        if USE_STUB_MODEL:
            log.info("Predictor running in STUB mode")
        elif USE_ONNX:
            self._load_onnx_models()
        else:
            self._load_pytorch_models()

    # -----------------------------------------------------------------------
    # Model loading
    # -----------------------------------------------------------------------

    def _load_pytorch_models(self):
        """
        MODE 2 — Load real SBERT (PyTorch) + LightGBM.
        This is the baseline serving option.
        """
        import pickle
        from sentence_transformers import SentenceTransformer

        log.info("Loading SBERT (PyTorch mode)...")
        self.sbert_model = SentenceTransformer("all-MiniLM-L6-v2")
        log.info("SBERT loaded")

        if not MODEL_PATH.exists():
            raise FileNotFoundError(
                f"Model not found at {MODEL_PATH}. "
                f"Run create_fake_model.py first."
            )
        with open(MODEL_PATH, "rb") as f:
            self.lgbm_model = pickle.load(f)
        log.info(f"LightGBM loaded from {MODEL_PATH}")

        with open(LABEL_ENCODER_PATH, "rb") as f:
            self.label_encoder = pickle.load(f)
        log.info("Label encoder loaded")

        self.model_version = "lgbm_v1_pytorch"

    def _load_onnx_models(self):
        """
        MODE 3 — Load SBERT exported to ONNX + LightGBM.
        ONNX runtime is faster than PyTorch on CPU because it applies
        graph optimizations and avoids Python overhead in the encoder.

        Requires:
            - models/sbert_onnx.onnx  (generated by export_onnx.py)
            - models/lgbm_classifier_v1.pkl
            - models/label_encoder.pkl
            pip install onnxruntime transformers
        """
        import pickle
        import onnxruntime as ort
        from transformers import AutoTokenizer

        if not ONNX_MODEL_PATH.exists():
            raise FileNotFoundError(
                f"ONNX model not found at {ONNX_MODEL_PATH}. "
                f"Run export_onnx.py first to generate it."
            )

        log.info(f"Loading ONNX session from {ONNX_MODEL_PATH}...")
        sess_options = ort.SessionOptions()
        sess_options.intra_op_num_threads = 2
        sess_options.inter_op_num_threads = 2
        sess_options.graph_optimization_level = (
            ort.GraphOptimizationLevel.ORT_ENABLE_ALL
        )
        self.onnx_session = ort.InferenceSession(
            str(ONNX_MODEL_PATH),
            sess_options=sess_options,
            providers=["CPUExecutionProvider"],
        )
        log.info("ONNX session loaded")

        log.info("Loading tokenizer...")
        self.tokenizer = AutoTokenizer.from_pretrained(
            "sentence-transformers/all-MiniLM-L6-v2"
        )
        log.info("Tokenizer loaded")

        if not MODEL_PATH.exists():
            raise FileNotFoundError(f"LightGBM model not found at {MODEL_PATH}")
        with open(MODEL_PATH, "rb") as f:
            self.lgbm_model = pickle.load(f)

        with open(LABEL_ENCODER_PATH, "rb") as f:
            self.label_encoder = pickle.load(f)

        log.info("ONNX predictor fully loaded")
        self.model_version = "lgbm_v1_onnx"

    # -----------------------------------------------------------------------
    # Prediction
    # -----------------------------------------------------------------------

    def predict(self, text: str, user_id: str) -> PredictionResult:
        start = time.time()

        if USE_STUB_MODEL:
            result = self._stub_predict(text)
        elif USE_ONNX:
            result = self._onnx_predict(text)
        else:
            result = self._pytorch_predict(text)

        result.latency_ms = round((time.time() - start) * 1000, 2)
        return result

    def _stub_predict(self, text: str) -> PredictionResult:
        """MODE 1 — keyword matching, no real model."""
        text_lower = text.lower()
        if any(w in text_lower for w in ["problem set", "due", "submit", "homework"]):
            top_label, top_conf = "Problem Set", round(random.uniform(0.82, 0.96), 2)
        elif any(w in text_lower for w in ["exam", "quiz", "midterm", "final"]):
            top_label, top_conf = "Exam", round(random.uniform(0.80, 0.95), 2)
        elif any(w in text_lower for w in ["syllabus", "office hours", "grading"]):
            top_label, top_conf = "Syllabus", round(random.uniform(0.85, 0.98), 2)
        elif any(w in text_lower for w in ["lecture", "theorem", "definition", "proof"]):
            top_label, top_conf = "Lecture Notes", round(random.uniform(0.75, 0.92), 2)
        else:
            top_label = random.choice(VALID_LABELS[:-1])
            top_conf  = round(random.uniform(0.55, 0.85), 2)

        remaining    = round(1.0 - top_conf, 2)
        second_conf  = round(remaining * 0.65, 2)
        third_conf   = round(remaining - second_conf, 2)
        others       = [l for l in VALID_LABELS if l != top_label]
        random.shuffle(others)

        return PredictionResult(
            predicted_tag   = top_label,
            confidence      = top_conf,
            action          = _determine_action(top_conf),
            top_predictions = [
                {"tag": top_label,   "confidence": top_conf},
                {"tag": others[0],   "confidence": second_conf},
                {"tag": others[1],   "confidence": third_conf},
            ],
            explanation     = None,
            model_version   = "stub_v0",
            latency_ms      = 0.0,
        )

    def _pytorch_predict(self, text: str) -> PredictionResult:
        """
        MODE 2 — Real SBERT (PyTorch) + LightGBM.
        SBERT encode() runs the full PyTorch transformer forward pass.
        """
        embedding = self.sbert_model.encode(
            text,
            normalize_embeddings=True,
            show_progress_bar=False,
        ).reshape(1, -1)

        probabilities = self.lgbm_model.predict_proba(embedding)[0]
        return self._build_result(probabilities, "lgbm_v1_pytorch")

    def _onnx_predict(self, text: str) -> PredictionResult:
        """
        MODE 3 — ONNX SBERT + LightGBM.

        Why ONNX is faster than PyTorch on CPU:
            PyTorch runs Python-level operations with dynamic graph building.
            ONNX runtime compiles the graph once and runs optimized C++ kernels.
            For CPU inference this gives a 1.5x-3x speedup on the encoder step.
            LightGBM inference is identical in both modes.
        """
        inputs = self.tokenizer(
            text,
            return_tensors="np",
            max_length=128,
            padding=True,
            truncation=True,
        )

        ort_inputs = {
            "input_ids":      inputs["input_ids"].astype(np.int64),
            "attention_mask": inputs["attention_mask"].astype(np.int64),
        }
        ort_outputs      = self.onnx_session.run(None, ort_inputs)
        token_embeddings = ort_outputs[0]   # shape: (1, 128, 384)

        # Mean pooling over non-padding tokens
        attention_mask = inputs["attention_mask"]
        mask_expanded  = attention_mask[:, :, np.newaxis].astype(np.float32)
        sum_embeddings = np.sum(token_embeddings * mask_expanded, axis=1)
        sum_mask       = np.clip(mask_expanded.sum(axis=1), a_min=1e-9, a_max=None)
        sentence_embedding = sum_embeddings / sum_mask  # shape: (1, 384)

        # L2 normalize
        norm = np.linalg.norm(sentence_embedding, axis=1, keepdims=True)
        sentence_embedding = sentence_embedding / np.clip(norm, a_min=1e-9, a_max=None)

        probabilities = self.lgbm_model.predict_proba(sentence_embedding)[0]
        return self._build_result(probabilities, "lgbm_v1_onnx")

    def _build_result(self, probabilities: np.ndarray, version: str) -> PredictionResult:
        """Shared result builder for PyTorch and ONNX modes."""
        top_idx       = int(np.argmax(probabilities))
        top_conf      = float(probabilities[top_idx])
        predicted_tag = self.label_encoder.inverse_transform([top_idx])[0]

        top3 = np.argsort(probabilities)[::-1][:3]
        top_predictions = [
            {
                "tag":        self.label_encoder.inverse_transform([i])[0],
                "confidence": round(float(probabilities[i]), 4),
            }
            for i in top3
        ]

        return PredictionResult(
            predicted_tag   = predicted_tag,
            confidence      = round(top_conf, 4),
            action          = _determine_action(top_conf),
            top_predictions = top_predictions,
            explanation     = None,
            model_version   = version,
            latency_ms      = 0.0,
        )


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _determine_action(confidence: float) -> str:
    if confidence >= AUTO_APPLY_THRESHOLD:
        return "auto_apply"
    elif confidence >= SUGGEST_THRESHOLD:
        return "suggest"
    else:
        return "no_tag"