FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    pandas==2.2.0 \
    pyarrow>=16.0.0 \
    scikit-learn==1.5.2 \
    lightgbm>=4.3.0 \
    mlflow==2.13.0 \
    psycopg2-binary>=2.9.9 \
    PyYAML>=6.0.1 \
    joblib>=1.4.0

COPY . .
