FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    requests==2.31.0 \
    psycopg2-binary==2.9.9 \
    mlflow==2.16.2 \
    prometheus-client==0.19.0

COPY app/monitor.py .
COPY app/feedback.py .

CMD ["python", "monitor.py"]
